//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnet_vj8
{
    using System;
    using System.Collections.Generic;
    
    public partial class natjecanje
    {
        public int id { get; set; }
        public string ime_plesaca { get; set; }
        public string ples { get; set; }
        public Nullable<int> ocjena { get; set; }
    }
}
